common/models/TblStudio.php
<?php

namespace common\models;

use Yii;
//use common\models\TblStudio;
use common\models\UProfile;
use common\models\TblAlbum;
use common\models\TblCategories;
use common\models\VerifyMember;
use common\models\Confirmation;
use yii\helpers\FileHelper;

/**
 * This is the model class for table "tbl_studio".
 *
 * @property int $id ID
 * @property int $userID userID
 * @property string $url url
 * @property string $studioName ชื่อสตูดิโอ
 * @property string $email email
 * @property string $tel เบอร์โทรศัพท์
 * @property string $lineID ไลน์ไอดี
 * @property string $placeOfWork สถานที่รับงาน
 * @property string $workType ประเภทงานที่รับ
 * @property string $coverImg ภาพพื้นหลัง
 */
class TblStudio extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $sid;
    public $searchstring;

    public static function tableName()
    {
        return 'tbl_studio';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['u_id', 'url', 'studioName'], 'required'],
            [['url'], 'unique'],
            ['url', 'match', 'pattern' => '/^[0-9A-Za-z-_]{6,25}$/'],
            [['u_id'], 'integer'],
            //[['placeOfWork'], 'string'],
            [['url', 'confirmation'], 'string', 'max' => 30],
            [['studioName'], 'string', 'max' => 100],
            [['tel'], 'string', 'max' => 10],
            [['lineID'], 'string', 'max' => 20],
            [['searchstring'], 'safe'],
            //[['workType'], 'string', 'max' => 50],
            [['cover_image'], 'file', 'extensions' => 'png, jpg, jpeg', 'maxSize' => 3072000, 'skipOnEmpty' => true],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Studio ID',
            'u_id' => 'u_id',
            'url' => 'url',
            'studioName' => 'ชื่อสตูดิโอ',
            //'email' => 'email',
            'tel' => 'เบอร์โทรศัพท์',
            'lineID' => 'ไลน์ไอดี',
            'placeOfWork' => 'สถานที่รับงาน',
            'workType' => 'ประเภทงานที่รับ',
            'coverImg' => 'ภาพพื้นหลัง',
            //'gimages' => 'uploadImage',
        ];
    }

    public function getIDPartner()
    {
        $id = Yii::$app->user->getId();
        $profileID = UProfile::find()->where(['userType' => 'P', 'u_id' => $id])->one();
        
        if (isset($profileID)) { 
            $sid = TblStudio::find()->where(['u_id' => $id])->one();
            if (!isset($sid)) {
                $sid = $sid->u_id;
            }
        }
        return $sid;
    }

    public function uploadCoverImage($id, $img)
    {
        $findStudio = TblStudio::findOne($id);
        // return $findUser->id;
        $dirName = 'profile'.$id;
        $path = Yii::getAlias('@app').'/web/uploads/profile/'.$dirName;
        FileHelper::createDirectory($path);
        $fileName = 'background-cover';
        // $files=\yii\helpers\FileHelper::findFiles('/path/to');
        // $delete = FileHelper::findFiles($path) ? unlink($path . '/' . $img) : null;
        $this->cover_image->saveAs($path . '/' . $fileName . '.' . $this->cover_image->extension);
        $fullName = $fileName . '.' . $this->cover_image->extension;
        return $fullName;
    }

    public function getUserProfile()
    {
        return $this->hasOne(UProfile::className(), ['id' => 'u_id']);
    }

    public function getAlbums()
    {
        return $this->hasMany(TblAlbum::className(), ['studioID' => 'id']);
    }

    public function getCategories()
    {
        return $this->hasMany(TblCategories::className(), ['s_id' => 'id']);
    }

    public function getVerifiedMember()
    {
        return $this->hasOne(VerifyMember::className(), ['studio_id' => 'id']);
    }

    public function getConfirmStatus()
    {
        return $this->hasOne(Confirmation::className(), ['confirm_id' => 'confirmation']);
    }
}

backend/controllers/TblStudioController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\TblStudio;
use common\models\TblStudioSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\TblGallery;
use common\models\TblAlbum;
use yii\db\Query;
use common\models\User;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;
use yii\widgets\ActiveField;
use common\models\UProfile;
use common\models\Locations;
use common\models\TblCategories;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\data\ActiveDataProvider;
use common\models\TblAlbumSearch;
/*use common\models\VerifyMember;
use common\models\VerifyMemberSearch;*/
/**
 * TblStudioController implements the CRUD actions for TblStudio model.
 */
class TblStudioController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'create_time',
                'updatedAtAttribute' => 'update_time',
                'value' => new Expression('NOW()'),//กำหนดค่า หรืออาจใช้ค่าอย่างอื่นที่ return เป็น timestamp ก็ได้
            ],
        ];
    }

    /**
     * Lists all TblStudio models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TblStudioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

   /* public function actionUploadform()
    {
        $upload = new TblGallery();
        $id = new User();
        $query = new Query();
        $id = Yii::$app->user->getId();
        $query->select('email')->from('user')->where('id = '.$id.'')->all();
        $command = $query->createCommand();
        $name = $command->queryAll();
        foreach ($name['0'] as $value) {
            $value;
        }

        if ($upload->load(Yii::$app->request->post())) {
            $upload->gimages = UploadedFile::getInstances($upload, 'gimages');
            if ($upload->gimages && $upload->validate()) {
                $path = '@app/uploads/user/'. $value;
                FileHelper::createDirectory($path);
                $upload->gimages->saveAs($path .'/'. $upload->gimages->baseName . '.' . $upload->gimages->extension);
                return true;
            } else {
                return false;
            }
            return $this->render('uploadform');
        }
        return $this->render('uploadform',[
            'upload' => $upload,
            'name' => $name,
            'id' => $id,
        ]);
    }*/

    public function actionUploadform($id)
    {
        $album = new TblAlbum();
        $model = new TblGallery();
        $studio = new TblStudio();
        $query = new Query();
        $qid = Yii::$app->user->getId();
        $query->select('id')->from('tbl_studio')->where('u_id = '.$qid.'')->all();
        $command = $query->createCommand();
        $idUser = $command->queryAll();
        foreach ($idUser['0'] as $value) {
            $value;
        }
        $albumName = 'Success';
        $cateAlubm = 'wedding';

        /*if ($album->load(Yii::$app->request->post())) {
            
            
            if ($album->save()) {
                return "save";
            } else {
                return "not save";
            }
        }*/

        /*$id = new User();
        $query = new Query();
        $id = Yii::$app->user->getId();
        $query->select('email')->from('user')->where('id = '.$id.'')->all();
        $command = $query->createCommand();
        $name = $command->queryAll();
        foreach ($name['0'] as $value) {
            $value;
        }*/

        $sid = TblStudio::findOne($id);
        //$modelStudio = TblStudio::findOne($id);

        if ($album->load(Yii::$app->request->post())) {
            $model->gimages = UploadedFile::getInstances($model, 'gimages');
            //$path = Yii::getAlias('@app').'/uploads/user/';
            $dirName = 'userid'.$value;
            $path = Yii::getAlias('@app').'/web/uploads/user/'.$dirName;
            FileHelper::createDirectory($path);

            $album->studioID = $sid->id;
            $album->image = $dirName.$model->gimages[0];
            $album->status = 'process';
            $arr = array();
            if($album->save()) {
                foreach ($model->gimages as $file) {
                    $newGallery = new TblGallery();
                    $newGallery->aID = $album->albumID;
                    $newGallery->status = 'process';
                    $newGallery->gName = $album->albumName;
                    $imgFullName = $dirName . $file->baseName . '.' . $file->extension;
                    //$file->saveAs($path . '/' . $value . $imgFullName);
                    $newGallery->gimages = $imgFullName;
                    /*$model->save();*/
                    if ($newGallery->save(false)) {
                        $file->saveAs($path . '/' . $imgFullName);
                    }
                    $arr[] = $imgFullName;
                }

                return print_r($arr);
            } else {
                return "upload fail.";
            }
            
            //if ($model->upload($value)) {
            
            //if ($album->validate()) {
                
                
                //return $album->albumName . " " . $album->type." ". $album->status;
                
            //}   
                //return $path;
            //}
        }

        return $this->render('uploadform', [
            'model' => $model,
            'album' => $album,
        ]);
    }

    /**
     * Displays a single TblStudio model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TblStudio model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TblStudio();
        $profile = new UProfile();
        $item = new Locations();
        $cate = new TblCategories();
        $occupation = $cate->addOccupation();
        $query = new Query();
        $id = Yii::$app->user->getId();
        $query->select('*')->from('uProfile')->where('u_id = '.$id.'')->all();
        $command = $query->createCommand();
        $name = $command->queryAll();
        foreach ($name as $value) {
            //$profile->email = $value['email'];
            $profile->u_id = $value['u_id'];
        }
        if ($model->load(Yii::$app->request->post())) {
            //return $this->redirect(['view', 'id' => $model->id]);
            //return $profile->email $profile->tel;
            //$model->email = $profile->email;
            //$model->tel = $profile->tel;

            //$transaction = Yii::$app->db->beginTransaction();
            //try {
            $model->u_id = $profile->u_id;
            $cate->s_id = $model->id;
            if ($model->save()) {
                //$transaction->commit();
                //return $this->render(['view', 'id' => $model->id]);
                $cate->s_id = $model->id;

                if ($cate->load(Yii::$app->request->post())) {
                $ar = $cate->workDetails;
                $pow = $cate->placeOfWork;
                $arr = array();
                $arr_results = array();

                $it = Yii::$app->request->post();
                //$arr = array();
                $listDetail = $cate->placeOfWork;
                if (is_array($listDetail)) {
                   foreach ($it['TblCategories']['placeOfWork'] as $key => $val) {
                        $arr[] = $val;
                    }
                }
                $cate->placeOfWork = json_encode($arr, JSON_UNESCAPED_UNICODE);
                //return print_r(json_decode($js));
                //return $js;

                foreach( $ar as $val )
                {
                  if( $val )
                  {
                    $arr_results[] = $val ;
                  }
                }
                $cate->workDetails = json_encode($arr_results);

                //return $js . " " . $js2. " ". $cate->cateWork;
                }

                if ($cate->save()) {
                    //return $this->redirect('index');
                    Yii::$app->db->createCommand()->update('uprofile', ['userType' => 'P'], 'id = '.$model->u_id.'')->execute();
                    return render('fanpage', ['id' => $model->id]);
                }
            }

                
                
                

            /*}  catch (\Exception $e) {
                $transaction->rollBack();
                return "fail";
            }*/
            //return $model->email . $model->tel;
        }

        return $this->render('create', [
            'model' => $model,
            'profile' => $profile,
            'item' => $item,
            'cate'=> $cate,
            'occupation' => $occupation,
        ]);
    }

    /**
     * Updates an existing TblStudio model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $cate = new TblCategories();
        $occupation = $cate->addOccupation();

backend/views/tbl-studio/_albumView.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

    <!-- <a href="#" class="thumbnail">
      <img src="https://i.pinimg.com/originals/c7/16/c7/c716c757a6f4ae3d198f04468163a2e4.jpg" alt="">
    </a> -->
    <div class="thumbnail">
    	<a href="<?= Url::to(['/tbl-album/detailgallery', 'id' => $model->albumID]); ?>">
	      	<img src="<?= $baseUrl.$model->image; ?>" alt="#">
	      	<div class="caption">
	        	<h4><?= $model->albumName; ?></h4>
	      	</div>
  		</a>
  	</div>

backend/views/tbl-studio/_form.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use yii\bootstrap\ActiveForm;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;
use yii\db\Query;
use common\models\Locations;

use unclead\multipleinput\MultipleInput;

/* @var $this yii\web\View */
/* @var $model common\models\TblStudio */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tbl-studio-form" >

    <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

    <!-- $form->field($model, 'gimages[]')->fileInput(['multiple' => true]) -->

    <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'studioName')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tel')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'lineID')->textInput(['maxlength' => true]) ?>

    <?= $form->field($cate, 'cateWork')->dropDownList($occupation,
    ['prompt'=>'กรุณาเลือกอาชีพ']) ?>

    <?= $form->field($cate, 'placeOfWork')->widget(MultipleInput::className(), [
        'max'               => 77,
        'min'               => 1, // should be at least 2 rows
        'allowEmptyList'    => false,
        'enableGuessTitle'  => true,
        'addButtonPosition' => MultipleInput::POS_HEADER,
        'columns' => [
        /*[
            'name'  => 'location_id',
            'type'  => 'dropDownList',
            'title' => 'location_name',
            'value' => function($data){
                             return $data['location_name'];
                        },
            'items' => 
            ArrayHelper::map(Locations::find()->orderBy(['location_id' => SORT_ASC])->all(), 'location_name', function($item){return $item->location_name;}),
        ],*/
        [
            'name' => 'location_name',
            'title' => 'จังหวัดที่รับงาน',
            'type'  => 'dropDownList',
            /*'value' => function($data){
                 return $data['placeOfWork'];
            },*/
            'items' => ArrayHelper::map(Locations::find()->orderBy(['location_name' => SORT_ASC])->all(), 'location_name', function($item){return $item->location_name;}),
            'enableError' => true,
            'options' => [
                'prompt' => 'เลือกจังหวัด',
                //'onchange' => '$(this).init_change();' //ส่งค่าไปเรียก Ajax
            ]
        ]
        ], // show add button in the header
    ])->label(false); ?>

    <h2>ประเภทงานที่รับและราคา</h2>

    <div class="border-price-div" id="hide-elements">
        <div class="inline form-inline" style="border-radius: 15px;">
            <?= $form->field($cate, 'workDetails[]')->checkbox(['uncheck' => null, 'class' => 'checkbox-inline-type', 'value' => 'congratulation'])->label(false); ?>          
            <?= Html::img(Yii::$app->request->baseUrl.'/img/pn1.png', ['alt'=>'some', 'class'=>'set-image']);?>
            <label class="checkbox-inline-type">รับปริญญา</label>
            <div class="input-price">
                <?= $form->field($cate, 'workDetails[]')->textInput(['type' => 'number', 'min' => 0, 'max' => 1000000, 'step' => 100, 'class' => 'price-box'])->label('ราคาครึ่งวัน', ['class' => 'control-label col-sm-6']) ?>
                <?= $form->field($cate, 'workDetails[]')->textInput(['type' => 'number', 'min' => 0, 'max' => 1000000, 'step' => 100, 'class' => 'price-box'])->label('ราคาเต็มวัน', ['class' => 'control-label col-sm-6']) ?>
            </div>
        </div>
        
        <div class="inline form-inline">
            <?= $form->field($cate, 'workDetails[]')->checkbox(['uncheck' => null, 'class' => 'checkbox-inline-type', 'value' => 'fashion'])->label(false); ?>    
            <?= Html::img(Yii::$app->request->baseUrl.'/img/pn2.png', ['alt'=>'some', 'class'=>'set-image']);?>
            <label class="checkbox-inline-type">ภาพบุคคล/แฟชั่น</label>
            <div class="input-price">
                <?= $form->field($cate, 'workDetails[]')->textInput(['type' => 'number', 'min' => 0, 'max' => 1000000, 'step' => 100, 'class' => 'price-box'])->label('ราคาครึ่งวัน', ['class' => 'control-label col-sm-6']) ?>
                <?= $form->field($cate, 'workDetails[]')->textInput(['type' => 'number', 'min' => 0, 'max' => 1000000, 'step' => 100, 'class' => 'price-box'])->label('ราคาเต็มวัน', ['class' => 'control-label col-sm-6']) ?>
            </div>
        </div>

        <div class="inline form-inline">
            <?= $form->field($cate, 'workDetails[]')->checkbox(['uncheck' => null, 'class' => 'checkbox-inline-type', 'value' => 'wedding'])->label(false); ?>    
            <?= Html::img(Yii::$app->request->baseUrl.'/img/pn3.png', ['alt'=>'some', 'class'=>'set-image']);?>
            <label class="checkbox-inline-type">งานแต่ง</label>
            <!-- <input type="hidden" name="quantity[]" value="-">
            <input type="hidden" name="quantity[]" value="-"> -->
        </div>

        <div class="inline form-inline">
            <?= $form->field($cate, 'workDetails[]')->checkbox(['uncheck' => null, 'class' => 'checkbox-inline-type', 'value' => 'pre-wedding'])->label(false); ?>    
            <?= Html::img(Yii::$app->request->baseUrl.'/img/pn4.png', ['alt'=>'some', 'class'=>'set-image']);?>
            <label class="checkbox-inline-type">พรีเวดดิ้ง</label>
            <!-- <input type="hidden" name="quantity[]" value="-">
            <input type="hidden" name="quantity[]" value="-"> -->
        </div>

        <div class="inline form-inline">
            <?= $form->field($cate, 'workDetails[]')->checkbox(['uncheck' => null, 'class' => 'checkbox-inline-type', 'value' => 'event'])->label(false); ?>    
            <?= Html::img(Yii::$app->request->baseUrl.'/img/pn5.png', ['alt'=>'some', 'class'=>'set-image']);?>
            <label class="checkbox-inline-type">งานอีเวนต์</label>
            <div class="input-price">
                <?= $form->field($cate, 'workDetails[]')->textInput(['type' => 'number', 'min' => 0, 'max' => 1000000, 'step' => 100, 'class' => 'price-box'])->label('ราคาครึ่งวัน', ['class' => 'control-label col-sm-6']) ?>
                <?= $form->field($cate, 'workDetails[]')->textInput(['type' => 'number', 'min' => 0, 'max' => 1000000, 'step' => 100, 'class' => 'price-box'])->label('ราคาเต็มวัน', ['class' => 'control-label col-sm-6']) ?>
            </div>
        </div>

        <div class="inline form-inline">
            <?= $form->field($cate, 'workDetails[]')->checkbox(['uncheck' => null, 'class' => 'checkbox-inline-type', 'value' => 'architecture'])->label(false); ?>    
            <?= Html::img(Yii::$app->request->baseUrl.'/img/pn6.png', ['alt'=>'some', 'class'=>'set-image']);?>
            <label class="checkbox-inline-type">สถาปัตยกรรม</label>
            <div class="input-price">
                <?= $form->field($cate, 'workDetails[]')->textInput(['type' => 'number', 'min' => 0, 'max' => 1000000, 'step' => 100, 'class' => 'price-box'])->label('ราคาครึ่งวัน', ['class' => 'control-label col-sm-6']) ?>
                <?= $form->field($cate, 'workDetails[]')->textInput(['type' => 'number', 'min' => 0, 'max' => 1000000, 'step' => 100, 'class' => 'price-box'])->label('ราคาเต็มวัน', ['class' => 'control-label col-sm-6']) ?>
            </div>
        </div>

        <div class="inline form-inline">
            <?= $form->field($cate, 'workDetails[]')->checkbox(['uncheck' => null, 'class' => 'checkbox-inline-type', 'value' => 'productAndFood'])->label(false); ?>    
            <?= Html::img(Yii::$app->request->baseUrl.'/img/pn7.png', ['alt'=>'some', 'class'=>'set-image']);?>
            <label class="checkbox-inline-type">สินค้า/อาหาร</label>
            <!-- <input type="hidden" name="quantity[]" value="-">
            <input type="hidden" name="quantity[]" value="-"> -->
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/tbl-studio/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\TblStudio */

$this->title = 'Create Tbl Studio';
$this->params['breadcrumbs'][] = ['label' => 'Tbl Studios', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tbl-studio-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'profile' => $profile,
        'item' => $item,
        'cate' => $cate,
        'occupation' => $occupation,
    ]) ?>

</div>

backend/views/tbl-studio/fanpage.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;
use kartik\dialog\Dialog;
use yii\widgets\ActiveForm;
?>
<head>

</head>
<body>

<div class="head-bg" style="background-image: url('http://backgroundcheckall.com/wp-content/uploads/2017/12/background-img-4.jpg')">

</div>

<div class="content">
    <div class="container">
    <section class="section-about">
        <div class="animate-up animated">
            <div class="section-box">
                <div class="profile">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="profile-photo">
                                <img src="https://blog.onabags.com/wp-content/uploads/2013/05/oliviaraejames.jpg">
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="profile-info">
                                <div class="profile-preword">
                                    <?php $form = ActiveForm::begin([
                                        //'action' =>['tbl-studio/uploadImageProfile'],
                                        'method' => 'post',
                                        'options' => ['enctype' => 'multipart/form-data']
                                    ]) ?>
                                    <span><?= $modelStudio->confirmation ?></span>
                                    <?php echo Dialog::widget();
                                    ?>
                                    
                                        <button type="button" id="btn-alert" class="btn btn-primary" style="float: right;">เปลี่ยนรูปภาพประจำตัว</button>
                                    <?php ActiveForm::end() ?>
                                </div>
                                <h1 class="profile-title">
                                    <span>I'm</span> <?= $modelStudio->studioName; ?>
                                </h1>
                                <h2 class="profile-position">ข้อมูลส่วนตัว</h2>
                            </div>
                            <ul class="profile-list">
                                <li class="clearfix">
                                    <strong class="title">ชื่อ</strong>
                                    <span class="cont"><?= $modelProfile->firstName."&nbsp". $modelProfile->lastName; ?></span>
                                </li>
                                <li class="clearfix">
                                    <strong class="title">เบอร์โทร</strong>
                                    <span class="cont"><?= $modelStudio->tel; ?></span>
                                </li>
                                <li class="clearfix">
                                    <strong class="title">อีเมล</strong>
                                    <span class="cont"><?= $modelProfile->email; ?></span>
                                </li>
                                <li class="clearfix">
                                    <strong class="title">ไลน์</strong>
                                    <span class="cont"><?= $modelStudio->lineID; ?></span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="profile-social">
                    <ul class="social">
                        <a><i class="glyphicon glyphicon-camera" style="font-size:24px"></i></a>
                        <a><!-- <i class="glyphicon glyphicon-briefcase" style="font-size:24px"></i> --></a>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="section section-skills">
        <div class="animate-up animated">
            <div class="section-title">
                <h2 class="inline-text">ช่างภาพ</h2>
                <p class="inline-text" style="float: right;">
                <?= Html::a('อัพโหลดรูป', Url::to(['tbl-studio/uploadform', 'id' => $modelStudio->id]), ['class' => 'btn btn-primary']) ?>
                </p>
            </div>
            
            <div class="section-box">
                <!-- <h1>
                    Hiiiiiiiiiiiiiiiiiiiiiiiiiiiii
                </h1> -->
            <?php 
                if ($modelAlbum !== NULL) {
                    echo ListView::widget([
                        'dataProvider' => $dataProvider,
                        'itemView' => '/tbl-studio/_albumView',
                        'summary' => false,
                        'itemOptions' => [
                            'class' => 'col-sm-6 col-md-3',
                        ],
                        'viewParams' => [
                            //'aName' => $aName,
                            'baseUrl' => $baseUrl,
                        ],
                    ]);
                }

                echo $id . " " . $tt->email . "<br>";
            ?>
                
            </div>
        </div>
    </section>
    </div>
</div>

</body>

<?php
/*message: 'เปลี่ยนรูปภาพโปรไฟล์: <input type="file" name = "pimage" class="form-control">'+'<br>'+
                'เปลี่ยนรูปภาพพื้นหลัง: <input type="file" name = "cimage" class="form-control">',*/
$js = <<< JS
$("#btn-alert").on("click", function() {
    var id = $modelStudio->id;
    BootstrapDialog.show({

            message: function (dialogItself) {
                var formupload = $('<form action="" method="POST"></form>');
                var plabel = 'เปลี่ยนรูปภาพโปรไฟล์:';
                var pinput = $('<input type="file" name="UProfile[imgProfile]" class="form-control">');
                var clabel = 'เปลี่ยนรูปภาพพื้นหลัง:';
                var cinput = $('<input type="file" name="cimage" class="form-control">');
                var button = $('<button type="submit" class="btn btn-primary">อับโหลด</button>');
                formupload.append(plabel).append(pinput).append(clabel).append(cinput).append(button);
                return formupload;
            },

            
            buttons: [{
                label: 'อับโหลด',
                type: 'submit',
                cssClass: 'btn-primary',
            }, {
                label: 'ยกเลิก',
                action: function(dialogRef) {
                    dialogRef.close();
                }
            }]
        });
});

JS;
 
// register your javascript
$this->registerJs($js);

?>

backend/views/tbl-studio/uploadimage.php
<?php
echo "hi";